name: Upload fastn-de to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - fastn-de.fifthtry.site/**
      - backend/**
      - .github/workflows/app-to-ft.yml


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_LETS_DE }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: cargo xtask publish-app
